# Generated by Django 4.2.5 on 2023-09-14 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('chaiperson', 'chairperson'), ('secretary', 'secretary'), ('finance manager', 'finance manager'), ('Product manager', 'Product manager')], max_length=100)),
                ('profilepic', models.ImageField(upload_to='media')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
